name: Build APK

on:
  workflow_dispatch:
  push:
    branches: [master]

env:
  UV_PYTHON: '3.12'
  FLET_CLI_NO_RICH_OUTPUT: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: astral-sh/setup-uv@v6

      - name: Install Flet
        run: uv pip install flet --system

      - name: Build APK
        run: flet build apk --project "Controle Financas" --org "com.github.tshonorio" --build-version "1.0.0" --yes --verbose

      - uses: actions/upload-artifact@v6
        with:
          name: controle-financas-apk
          path: build/apk/
